import User from '../models/User.js';
import { generateToken } from '../utils/jwt.js';
import { OAuth2Client } from 'google-auth-library';
import { addCredits } from './creditController.js';

// @desc    Register user with email and password
// @route   POST /api/auth/register
// @access  Public
export const register = async (req, res) => {
  try {
    const { name, email, password, referralCode: referredByCode } = req.body;

    // Validate input
    if (!name || !email || !password) {
      return res.status(400).json({
        success: false,
        message: 'Please provide all required fields',
      });
    }

    // Check if user already exists
    const existingUser = await User.findOne({ email });
    if (existingUser) {
      return res.status(400).json({
        success: false,
        message: 'User already exists with this email',
      });
    }

    // Handle referral if code provided
    let referrerId = null;
    if (referredByCode) {
      const referrer = await User.findOne({ referralCode: referredByCode });
      if (referrer) {
        referrerId = referrer._id;
      }
    }

    // Create user (referralCode will be auto-generated by pre-save hook)
    const user = await User.create({
      name,
      email,
      password,
      authProvider: 'local',
      referredBy: referrerId,
    });

    // Seed free tier benefits + log
    user.allowedModels = ['chatgpt', 'perplexity', 'google_ai_overview'];
    user.currentPlan = 'free';
    user.subscriptionTier = 'free';
    await user.save();
    await addCredits(
      user._id,
      25,
      'earned',
      'trial',
      'Signup bonus (free tier)'
    );

    // Award referral credits if referred
    if (referrerId) {
      try {
        // Award 10 credits to referrer
        await addCredits(
          referrerId,
          10,
          'earned',
          'referral',
          `Referred ${user.name}`,
          { referredUserId: user._id, referredUserEmail: user.email }
        );

        // Increment referral count
        await User.findByIdAndUpdate(referrerId, {
          $inc: { referralCount: 1 },
        });
      } catch (error) {
        console.error('Error awarding referral credits:', error);
      }
    }

    // Send token response
    sendTokenResponse(user, 201, res);
  } catch (error) {
    console.error('Register error:', error);
    res.status(500).json({
      success: false,
      message: 'Error registering user',
      error: error.message,
    });
  }
};

// @desc    Login user with email and password
// @route   POST /api/auth/login
// @access  Public
export const login = async (req, res) => {
  try {
    const { email, password } = req.body;

    // Validate input
    if (!email || !password) {
      return res.status(400).json({
        success: false,
        message: 'Please provide email and password',
      });
    }

    // Find user and include password field
    const user = await User.findOne({ email }).select('+password');

    if (!user) {
      return res.status(401).json({
        success: false,
        message: 'Invalid credentials',
      });
    }

    // Check if user registered with OAuth
    if (user.authProvider !== 'local') {
      return res.status(400).json({
        success: false,
        message: `This account is registered with ${user.authProvider}. Please use ${user.authProvider} to login.`,
      });
    }

    // Check password
    const isPasswordMatch = await user.comparePassword(password);

    if (!isPasswordMatch) {
      return res.status(401).json({
        success: false,
        message: 'Invalid credentials',
      });
    }

    // Update last login
    user.lastLogin = Date.now();
    await user.save();

    // Send token response
    sendTokenResponse(user, 200, res);
  } catch (error) {
    console.error('Login error:', error);
    res.status(500).json({
      success: false,
      message: 'Error logging in',
      error: error.message,
    });
  }
};

// @desc    Google OAuth login/register
// @route   POST /api/auth/google
// @access  Public
export const googleAuth = async (req, res) => {
  try {
    const { credential, referralCode: referredByCode } = req.body;

    if (!credential) {
      return res.status(400).json({
        success: false,
        message: 'Google credential is required',
      });
    }

    // Initialize Google OAuth2 client
    const client = new OAuth2Client(process.env.GOOGLE_CLIENT_ID);

    // Verify Google token
    const ticket = await client.verifyIdToken({
      idToken: credential,
      audience: process.env.GOOGLE_CLIENT_ID,
    });

    const payload = ticket.getPayload();
    const { email, name, picture, sub: googleId } = payload;

    if (!email) {
      return res.status(400).json({
        success: false,
        message: 'Email not provided by Google',
      });
    }

    // Check if user exists
    let user = await User.findOne({ email });

    if (user) {
      // User exists - update last login
      user.lastLogin = Date.now();
      await user.save();
    } else {
      // Handle referral if code provided
      let referrerId = null;
      if (referredByCode) {
        const referrer = await User.findOne({ referralCode: referredByCode });
        if (referrer) {
          referrerId = referrer._id;
        }
      }

      // Create new user (referralCode will be auto-generated by pre-save hook)
      user = await User.create({
        name: name || email.split('@')[0],
        email,
        authProvider: 'google',
        googleId,
        avatar: picture,
        isEmailVerified: true,
        referredBy: referrerId,
      });

      // Seed free tier benefits for new Google users + log
      user.allowedModels = ['chatgpt', 'perplexity', 'google_ai_overview'];
      user.currentPlan = 'free';
      user.subscriptionTier = 'free';
      await user.save();
      await addCredits(
        user._id,
        25,
        'earned',
        'trial',
        'Signup bonus (free tier)'
      );

      // Award referral credits if referred
      if (referrerId) {
        try {
          // Award 10 credits to referrer
          await addCredits(
            referrerId,
            10,
            'earned',
            'referral',
            `Referred ${user.name}`,
            { referredUserId: user._id, referredUserEmail: user.email }
          );

          // Increment referral count
          await User.findByIdAndUpdate(referrerId, {
            $inc: { referralCount: 1 },
          });
        } catch (error) {
          console.error('Error awarding referral credits:', error);
        }
      }
    }

    // Send token response
    sendTokenResponse(user, 200, res);
  } catch (error) {
    console.error('Google auth error:', error);
    res.status(500).json({
      success: false,
      message: 'Error with Google authentication',
      error: error.message,
    });
  }
};

// @desc    Get current logged in user
// @route   GET /api/auth/me
// @access  Private
export const getMe = async (req, res) => {
  try {
    const user = await User.findById(req.user.id);

    res.status(200).json({
      success: true,
      user,
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Error fetching user',
      error: error.message,
    });
  }
};

// @desc    Logout user / clear cookie
// @route   POST /api/auth/logout
// @access  Private
export const logout = async (req, res) => {
  try {
    res.cookie('token', 'none', {
      expires: new Date(Date.now() + 10 * 1000),
      httpOnly: true,
      secure: process.env.NODE_ENV === 'production',
      sameSite: process.env.NODE_ENV === 'production' ? 'none' : 'lax',
    });

    res.status(200).json({
      success: true,
      message: 'User logged out successfully',
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Error logging out',
      error: error.message,
    });
  }
};

// @desc    Update user password
// @route   PUT /api/auth/updatepassword
// @access  Private
export const updatePassword = async (req, res) => {
  try {
    const { currentPassword, newPassword } = req.body;

    if (!currentPassword || !newPassword) {
      return res.status(400).json({
        success: false,
        message: 'Please provide current and new password',
      });
    }

    const user = await User.findById(req.user.id).select('+password');

    // Check if user uses OAuth
    if (user.authProvider !== 'local') {
      return res.status(400).json({
        success: false,
        message: 'Cannot update password for OAuth users',
      });
    }

    // Check current password
    const isMatch = await user.comparePassword(currentPassword);

    if (!isMatch) {
      return res.status(401).json({
        success: false,
        message: 'Current password is incorrect',
      });
    }

    user.password = newPassword;
    await user.save();

    sendTokenResponse(user, 200, res);
  } catch (error) {
    res.status(500).json({
      success: false,
      message: 'Error updating password',
      error: error.message,
    });
  }
};

// Helper function to get token from model, create cookie and send response
const sendTokenResponse = (user, statusCode, res) => {
  // Create token
  const token = generateToken(user._id);

  const options = {
    expires: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days
    httpOnly: true,
    secure: process.env.NODE_ENV === 'production', // true in production
    sameSite: process.env.NODE_ENV === 'production' ? 'none' : 'lax', // 'none' for cross-origin in production
  };

  res.status(statusCode).cookie('token', token, options).json({
    success: true,
    token,
    user: {
      id: user._id,
      name: user.name,
      email: user.email,
      avatar: user.avatar,
      authProvider: user.authProvider,
      credits: user.credits,
    },
  });
};

export default {
  register,
  login,
  googleAuth,
  getMe,
  logout,
  updatePassword,
};
